language: c   # placeholder
service:
  - docker

matrix:
  include:
    - env: SYS=debian

before_script:
  - export IMG_NAME=arnoldosmium/docker-conda-in-docker

script:
  - cd $SYS && docker build -t ${IMG_NAME}:${SYS}-dev .

before_deploy:
  - secure: "yH5k9f7kY6iOlUzopRxri8JrRaR31/m1q545uc6j6wF5IVHmbSnvoQbQoEj0MQoz1KYirPdJbWc9VHUwjdT/n3cezmUQHx1w7MLoMGZ/JVkl6ANpwv644MXRBOoftcMLu1rVa7Ho+m7Lu1wJspbANOWejZKjhTogpH0CTcqLSxLAWuiyiC8bMXfSOABeqoYjK6hEUiYXA8VoO6xJedN8HDU3w4ezbO1TVVaiIQAlj8WSvADBzZORZLMpHdIkdOEj4GVLQyR0RCJrf/fpc89GPbkMZTZ6DA28IlCB8iYgrxe1xyaP70kREV9rT+Hf7PiAZqUnBEODuJuthztjvkfO9h7tgDT2NXwmR3jOk2mQwVaXnGcNi+lQBE+L4N1YjwLEIUlZWPSZkiU6KOkEmtaxhwF9fiay1SeZRBZaSQJ5y5BYiYz4SlVz7MsOTZrDx47L8Ae/8EPYbtWenpnmvKXnmQ9B0zTkPGj+gWmt7q1M7K7z7x55Gq1QOJI/pQ173O3ibg7L/ubKGrkMa0V2qS6D6zLJVZkaErBlWmsXHQ6Ra4/8mv86NGFh25jVCEyjqESNUy3ZCoZN7jaHNCa7IBPUgZ5OlmaAFYACOm0SI0tWc7KSfS+hojvbCwblf7NBWRguK4vLapxNxUSI7t1+Azps1M+Uk9H+KZ341FhpaMAHKGE="

deploy:
  - provider: script
    script: docker push ${IMG_NAME}:${SYS}-dev
    on:
      branch: fix-deployx