language: c   # placeholder
service:
  - docker

matrix:
  include:
    - env: SYS=debian

env:
  - secure: "UUNJIMWqrQ+k7fYz1azhMwGJDAVN0lFg83Aptau/yYf21JTt8msDM/Km7LJOI0+QvRFBggO8h8S36Xhc2zaAeU09j0hwaAJNhReelTdVTmYpC8yn5xU5dd81IcQs8utnqaSV2jL55Gtpn1/N+gvDhmnEPrLbnZos1In6EIbWlgPxwdxUy178DcalMPyGMfEW84+jaghHqYO8NERHdcYQWs6ezgExYlYy11xfWBPcOERbM7/sikodF9PKu3S9U9LW+xfRgTWE2P9VSqd1A4FM5AK/I0E2T+gL0IcZwWDzhHD6AZcdx5+1Ja46AjW03/vHcvDNph8PAzCygprDqRZD32JcBsRHlwaawr0YV2I3pKixyJTzZiK0reST4vGyx05CnHaVjb+yHOCbdGw57fV09HeJ7JldcmDmjFqdOpoPirZVaY08sPcZn2w/2Regj09G+6rLpEcIPWOL3eF+5fBS5vmxqFbzzHLxqCvw+1ZpdciAuZdaqW0xogJjoMULw+vyCEtJjw4t1C6o+5h1FcGGNyZBv5z44JdFXHDNrYGqJ36dzgwykWPIEIzLfM++2oh4Th2xKbgSKdJTwZtj1j7jcnLjp6cgzSqwtrIMSgNtF1vFZOydvxCL66y6hG8+kLL0XXHRmeCJFkFggO2wmhxNKmBYAKM5MwA8gIsnGTKR9/8="

before_script:
  - export IMG_NAME=arnoldosmium/docker-conda-in-docker
  - echo $BAD
  - secure: "DBq+Dz8mnf+e+72VKJ319/p2+lOqeNbauH/4FA18XfgehVer3xzZ2UjiihhEAk2c8don6aFDA3SA88TbwnKNmLjNI+8p/JvYcOI1cZCumrkEREDW0DIWEIgTe9hQRR/jOLSB80cm5aKxgiwZ8LUM7mRaA3WRBTROIeSbNTo8eo90Obkry42u+FZhyYXW5KCuuMXFStrg/yWOtdSrfIVodJYpoVp6y7wHmaNdvG2UmwqtJETWlCFjLHWkPkkq/l7SMItReZ0dSv6dfr8YZDJh8qJE2kD5KfW9qQHJpZAqe/jM9YNbaf1u+KLrObtfGddcrGdvSZPX1TqEZf0bPQo9WFSSkS1akCwPMHFlJSL0sr5QE4hPbp9pCZ6DG0phbgYw/FhT/ihKhP7DSQWikmctUUEf84LgX+sRD2uj2lYiJSFTIPR1V8PHmwEUXW/F8dO7d6wOAWtXmbBLjYkaGa9uQaOo6s/gO4SOBF8XNK+GqYGTWMFt4eUA+E97eck0jpfMBdn2sfSNqF36nrx1lF7rmF+l9nnfJtMDlatvXJbj6UELRPm4T1bHErHqMOitgjvwfnUKAt4kEUh0TsQ9Vzh3dlUQdjoCThFNgupIBjPKAN/+jfj4+0IHY4XYdoembYezHAIJdKe8AXVGuX1mXyhrYRHP9rVbChe6ljKIObUh6/k="

script:
  - cd $SYS && docker build -t ${IMG_NAME}:${SYS}-dev .

before_deploy:
  - secure: "yH5k9f7kY6iOlUzopRxri8JrRaR31/m1q545uc6j6wF5IVHmbSnvoQbQoEj0MQoz1KYirPdJbWc9VHUwjdT/n3cezmUQHx1w7MLoMGZ/JVkl6ANpwv644MXRBOoftcMLu1rVa7Ho+m7Lu1wJspbANOWejZKjhTogpH0CTcqLSxLAWuiyiC8bMXfSOABeqoYjK6hEUiYXA8VoO6xJedN8HDU3w4ezbO1TVVaiIQAlj8WSvADBzZORZLMpHdIkdOEj4GVLQyR0RCJrf/fpc89GPbkMZTZ6DA28IlCB8iYgrxe1xyaP70kREV9rT+Hf7PiAZqUnBEODuJuthztjvkfO9h7tgDT2NXwmR3jOk2mQwVaXnGcNi+lQBE+L4N1YjwLEIUlZWPSZkiU6KOkEmtaxhwF9fiay1SeZRBZaSQJ5y5BYiYz4SlVz7MsOTZrDx47L8Ae/8EPYbtWenpnmvKXnmQ9B0zTkPGj+gWmt7q1M7K7z7x55Gq1QOJI/pQ173O3ibg7L/ubKGrkMa0V2qS6D6zLJVZkaErBlWmsXHQ6Ra4/8mv86NGFh25jVCEyjqESNUy3ZCoZN7jaHNCa7IBPUgZ5OlmaAFYACOm0SI0tWc7KSfS+hojvbCwblf7NBWRguK4vLapxNxUSI7t1+Azps1M+Uk9H+KZ341FhpaMAHKGE="

deploy:
  - provider: script
    script: docker push ${IMG_NAME}:${SYS}-dev
    on:
      branch: fix-deployx