language: c   # placeholder
service:
  - docker

matrix:
  include:
    - env: SYS=debian

env:
  global:
    secure: "NQNwN5y5Y/Cgyze22YqGL1cMxZjVW2MJNiQs+ryzueNJx6N9uHGDe6cpeiT+HFhK8FFGwwc2p1Jd/sU1vBQAq5m0CQKsHS6xBjPlfCPPdZSos884ce6kgqsV3OmqMm1iI2rMEmaqmi9jn4ABf3Wjz1qmdDS7ep5NyZ86sV/ApUWhLFFWnkz5gBSV4eYfrHXNWbdlnljwHg2yJrkd+OH4ytiFrY1ZWpd/uPC/hFYZvMyi/sIMpRVCZlnpwjVoEOBfknbMxMcW+Eoy16dxsmMDLkCHMgTpO2NFr851U1l7aNi0ATtOUUmw/xvf3Ug6zRWo0qX0H9ymBFqsiQIZEHMKvwDsJkBDXBCNmeYqnFjOLBG9pDxzYq2zPp5exKv45Bm/+rntbRoBYyZj47DC82JQnaG5Op6+DwWdbosreQ5Hw5s1Hu0PdxiZHHSW4YXMk4Uncvs64fww8weQwTbPXxrcFVpeATanx7BTwekMT3JPgKk4lsd3+Zyu9dbkkp3lXzMMuK+AMR4ru+Ps0ptj/SYu6dhkLgtvLdrKnNIv2cDtVJgOSzUQt3avBWwrMywoQ7saa0jUTRN42AVet6CGM5qsbxp9FnReRDyndBZNv4QELuKsoOh/5L/KiAmrJloVNJhsbYSXG74s88WpK2c29+U0Bfr8Qs2hLWfwpNQv5tPH9aA="

before_script:
  - export IMG_NAME=arnoldosmium/docker-conda-in-docker

script:
  - cd $SYS && docker build -t ${IMG_NAME}:${SYS}-dev .

before_deploy:
  - docker login -u arnoldosmium -p $P
  - export TAG=$(git describe --tags)

deploy:
  - provider: script
    script: docker push ${IMG_NAME}:${SYS}-dev
    on:
      branch: master
  - provider: script
    script: docker tag ${IMG_NAME}:${SYS}-dev ${IMG_NAME}:${SYS}-${TAG} && docker push ${IMG_NAME}:${SYS}-${TAG}
    on:
      tags: true